artifact_location: /home/anatoly/PycharmProjects/YOLOv8Baseline/src/train/runs/mlflow/0
creation_time: 1698053297351
experiment_id: '0'
last_update_time: 1698053297351
lifecycle_stage: active
name: Default
