training_params:
  model: yolov8n-seg.pt
  data: data.yaml
  imgsz: 512
  epochs: 50
  patience: 100
  batch: 16
  device: 0
  workers: 12
  optimizer: AdamW
  seed: 12345
  cos_lr: True
  lr0: 0.001
  task: InstanceSegmentsRes
  name: YOLOv8_ver0
  show_labels: False
  mode: train
  single_cls: False
  amp: False
  save_json: True
  half: False
  mosaic: 0
  flipud: 0.5
  fliplr: 0.5
  degrees : 0.5